import type { Best50Painter } from "@maimai/painter/best50";
import type { ProfileModule } from "@maimai/painter/modules/profile";
import type { ScoreGridModule } from "@maimai/painter/modules/scoreGrid";
import { hitokoto, type ImageOptions, image, text } from "@theme-tools/common/elements";
import { maimaiDifficultyColors } from "@theme-tools/common/palette";
import type { ThemeContext } from "@theme-tools/lib/context";
import type { SpriteDirs } from "@theme-tools/lib/sprites";
import {
    type MaimaiAchievementKey,
    type MaimaiDxRatingKey,
    type MaimaiMilestoneKey,
    type MaimaiModeKey,
    maimaiAchievements,
    maimaiBest50Versionless,
    maimaiDxRating,
    maimaiMilestones,
    maimaiModes,
} from "@theme-tools/maimai/sprites";
import type { z } from "zod/v4";

export type Best50Theme = z.input<typeof Best50Painter.THEME>;
type ScoreGridElement = z.input<typeof ScoreGridModule.SCHEMA>;
type ProfileElement = z.input<typeof ProfileModule.SCHEMA>;

/**
 * Everything a maimai best50 theme varies. The layout itself is shared: only the artwork, the
 * sprite pools it borrows from, and the accent colour change between versions.
 */
export interface MaimaiBest50Options {
    /**
     * Theme id without the orientation suffix, for example `jp-prism`.
     */
    name: string;
    /**
     * Display name without the orientation suffix.
     */
    displayName: string;
    /**
     * Appended after the orientation, for example ` (April Fools 2026)`.
     */
    displayNameSuffix?: string;
    borderColor: string;
    /**
     * Domain used in the footer and to pick the hitokoto support file.
     */
    brand?: "maimaidx" | "maimai";
    achievements: SpriteDirs<MaimaiAchievementKey>;
    milestones?: SpriteDirs<MaimaiMilestoneKey>;
    modes: SpriteDirs<MaimaiModeKey>;
    dxRating: SpriteDirs<MaimaiDxRatingKey>;
}

interface GridPlacement {
    x: number;
    y: number;
    horizontalSize: number;
    verticalSize: number;
    region: "new" | "old";
}

function scoreGrid(ctx: ThemeContext, options: MaimaiBest50Options, placement: GridPlacement): ScoreGridElement {
    return {
        type: "score-grid",
        x: placement.x,
        y: placement.y,
        horizontalSize: placement.horizontalSize,
        verticalSize: placement.verticalSize,
        region: placement.region,
        index: 0,
        scoreBubble: {
            width: 280,
            height: 155,
            margin: 10,
            gap: 20,
            color: maimaiDifficultyColors,
        },
        sprites: {
            achievement: maimaiAchievements(ctx, options.achievements),
            mode: maimaiModes(ctx, options.modes),
            milestone: maimaiMilestones(ctx, options.milestones),
        },
    };
}

function profile(ctx: ThemeContext, options: MaimaiBest50Options, placement: { x: number; y: number; height: number }): ProfileElement {
    return {
        type: "profile",
        x: placement.x,
        y: placement.y,
        height: placement.height,
        sprites: {
            dxRating: maimaiDxRating(ctx, options.dxRating),
            dxRatingNumberMap: ctx.ref(`${maimaiBest50Versionless}/dxRating/numberMap.webp`),
            profile: {
                nameplate: ctx.ref(`${maimaiBest50Versionless}/nameplate.webp`),
                icon: ctx.ref(`${maimaiBest50Versionless}/icon.webp`),
            },
        },
    };
}

function hitokotoLines(brand: string) {
    return ["hitokoto/general.json", `hitokoto/support/${brand}.json`];
}

export function maimaiBest50Landscape(ctx: ThemeContext, options: MaimaiBest50Options, images: ImageOptions[]): Best50Theme {
    const brand = options.brand ?? "maimaidx";
    const borderColor = options.borderColor;
    return {
        displayName: `${options.displayName}, Landscape${options.displayNameSuffix ?? ""}`,
        name: `${options.name}-landscape`,
        width: 2560,
        height: 1440,
        elements: [
            ...images.map((img) => image(ctx, img)),
            scoreGrid(ctx, options, { x: 70, y: 500, horizontalSize: 3, verticalSize: 5, region: "new" }),
            scoreGrid(ctx, options, { x: 1010, y: 150, horizontalSize: 5, verticalSize: 7, region: "old" }),
            profile(ctx, options, { x: 110, y: 345, height: 129 }),
            text({
                size: 32,
                x: 2480,
                y: 1407,
                borderColor,
                align: "right",
                content: `Generated by saltbot | ${brand}.cab/discord | ${brand}.cab/invite`,
            }),
            text({ size: 24, x: 1030, y: 100, borderColor, align: "left", content: "{newScoreRatingAvgString}\n{oldScoreRatingAvgString}" }),
            text({ size: 24, x: 1355, y: 100, borderColor, align: "left", content: "{newScoreMilestone}\n{oldScoreMilestone}" }),
            hitokoto(ctx, {
                size: 24,
                x: 80,
                y: 1403,
                borderColor,
                align: "left",
                width: 1000,
                linebreak: true,
                probability: 0.1,
                customLines: hitokotoLines(brand),
            }),
            text({ size: 32, x: 40, y: 72, borderColor, align: "left", content: "{dateTime}" }),
        ],
    };
}

export function maimaiBest50Portrait(ctx: ThemeContext, options: MaimaiBest50Options, images: ImageOptions[]): Best50Theme {
    const brand = options.brand ?? "maimaidx";
    const borderColor = options.borderColor;
    return {
        displayName: `${options.displayName}, Portrait${options.displayNameSuffix ?? ""}`,
        name: `${options.name}-portrait`,
        width: 1560,
        height: 2315,
        elements: [
            ...images.map((img) => image(ctx, img)),
            scoreGrid(ctx, options, { x: 40, y: 440, horizontalSize: 5, verticalSize: 3, region: "new" }),
            scoreGrid(ctx, options, { x: 40, y: 1015, horizontalSize: 5, verticalSize: 7, region: "old" }),
            profile(ctx, options, { x: 580, y: 145, height: 150 }),
            text({ size: 32, x: 60, y: 2280, borderColor, align: "left", content: "Generated by saltbot |" }),
            text({ size: 28, x: 445, y: 2260, borderColor, align: "left", content: `${brand}.cab/invite\n${brand}.cab/discord` }),
            text({ size: 24, x: 50, y: 390, borderColor, align: "left", content: "{newScoreRatingAvgString}\n{oldScoreRatingAvgString}" }),
            text({ size: 24, x: 370, y: 390, borderColor, align: "left", content: "{newScoreMilestone}\n{oldScoreMilestone}" }),
            text({ size: 30, x: 780, y: 370, borderColor, align: "center", content: "{level50Title}" }),
            text({ size: 18, x: 780, y: 400, borderColor, align: "center", content: "{level50Subtitle}" }),
            hitokoto(ctx, {
                size: 24,
                x: 1500,
                y: 2260,
                borderColor,
                align: "right",
                width: 580,
                linebreak: true,
                probability: 0.1,
                customLines: hitokotoLines(brand),
            }),
            text({ size: 32, x: 1500, y: 125, borderColor, align: "right", content: "{dateTime}" }),
        ],
    };
}
