import type { FolderPainter } from "@maimai/painter/folder";
import type { FolderModule } from "@maimai/painter/modules/folder";
import type { ProfileModule } from "@maimai/painter/modules/profile";
import { hitokoto, type ImageOptions, image, text } from "@theme-tools/common/elements";
import { maimaiDifficultyColors } from "@theme-tools/common/palette";
import type { ThemeContext } from "@theme-tools/lib/context";
import type { SpriteDirs } from "@theme-tools/lib/sprites";
import {
    type MaimaiAchievementKey,
    type MaimaiDxRatingKey,
    type MaimaiMilestoneKey,
    maimaiAchievements,
    maimaiBest50Versionless,
    maimaiDxRating,
    maimaiMilestones,
} from "@theme-tools/maimai/sprites";
import type { z } from "zod/v4";

export type FolderTheme = z.input<typeof FolderPainter.THEME>;
type FolderElement = z.input<typeof FolderModule.SCHEMA>;
type ProfileElement = z.input<typeof ProfileModule.SCHEMA>;

/**
 * Id of the folder card, so the canvas can grow with it.
 */
const folderCardId = "folders";

export interface MaimaiFolderOptions {
    name: string;
    displayName: string;
    borderColor: string;
    /**
     * Fill of the folder card.
     */
    cardColor: string;
    achievements: SpriteDirs<MaimaiAchievementKey>;
    milestones?: SpriteDirs<MaimaiMilestoneKey>;
    dxRating: SpriteDirs<MaimaiDxRatingKey>;
    /**
     * Jackets on every row of a folder.
     */
    horizontalSize?: number;
}

function folderCard(ctx: ThemeContext, options: MaimaiFolderOptions): FolderElement {
    return {
        type: "folder",
        x: 40,
        y: 300,
        id: folderCardId,
        width: 1480,
        height: 400,
        margin: 30,
        gap: 30,
        horizontalSize: options.horizontalSize ?? 10,
        color: { card: options.cardColor },
        title: { size: 40, gap: 15, borderColor: options.borderColor },
        jacket: { size: 130, gap: 10, margin: 10 },
        bubble: { color: maimaiDifficultyColors },
        sprites: {
            achievement: maimaiAchievements(ctx, options.achievements),
            milestone: maimaiMilestones(ctx, options.milestones),
        },
    };
}

function profile(ctx: ThemeContext, options: MaimaiFolderOptions): ProfileElement {
    return {
        type: "profile",
        x: 580,
        y: 145,
        height: 150,
        sprites: {
            dxRating: maimaiDxRating(ctx, options.dxRating),
            dxRatingNumberMap: ctx.ref(`${maimaiBest50Versionless}/dxRating/numberMap.webp`),
            profile: {
                nameplate: ctx.ref(`${maimaiBest50Versionless}/nameplate.webp`),
                icon: ctx.ref(`${maimaiBest50Versionless}/icon.webp`),
            },
        },
    };
}

/**
 * Layout for the maimai folder painter.
 *
 * The folder card is the only module in the repository that genuinely grows, so this is also the
 * only layout that uses `id` and `layout.contributors`: the canvas is as tall as the folders need,
 * and the footer anchors to the bottom of the grown canvas rather than to a fixed coordinate.
 *
 * No theme uses this yet. `width` and `height` are minimums, but the coordinates below have not been
 * checked against a render, so a theme adopting this should be tuned against
 * `npm test -- painter/maimai/folder`.
 */
export function maimaiFolder(ctx: ThemeContext, options: MaimaiFolderOptions, images: ImageOptions[]): FolderTheme {
    const borderColor = options.borderColor;
    return {
        displayName: options.displayName,
        name: options.name,
        width: 1560,
        height: 800,
        layout: { contributors: [folderCardId] },
        elements: [
            ...images.map((img) => image(ctx, img)),
            folderCard(ctx, options),
            profile(ctx, options),
            text({
                size: 32,
                x: -80,
                y: -35,
                borderColor,
                align: "right",
                content: "Generated by saltbot | maimaidx.cab/discord | maimaidx.cab/invite",
                anchor: { location: "bottom_right" },
            }),
            hitokoto(ctx, {
                size: 24,
                x: 80,
                y: -35,
                borderColor,
                align: "left",
                width: 1000,
                linebreak: true,
                probability: 0.1,
                customLines: ["hitokoto/general.json", "hitokoto/support/maimaidx.json"],
                anchor: { location: "bottom_left" },
            }),
            text({ size: 32, x: 1500, y: 125, borderColor, align: "right", content: "{dateTime}" }),
        ],
    };
}
