import type { BestPainter } from "@chunithm/painter/best";
import type { ProfileModule } from "@chunithm/painter/modules/profile";
import type { ScoreGridModule } from "@chunithm/painter/modules/scoreGrid";
import {
    type ChunithmAchievementKey,
    type ChunithmRatingNumberMapKey,
    chunithmAchievements,
    chunithmMilestones,
    chunithmProfile,
    chunithmRatingNumberMap,
} from "@theme-tools/chunithm/sprites";
import { hitokoto, type ImageOptions, image, text } from "@theme-tools/common/elements";
import { chunithmDifficultyColors } from "@theme-tools/common/palette";
import type { ThemeContext } from "@theme-tools/lib/context";
import type { SpriteDirs } from "@theme-tools/lib/sprites";
import type { z } from "zod/v4";

export type ChunithmBestTheme = z.input<typeof BestPainter.THEME>;
type ScoreGridElement = z.input<typeof ScoreGridModule.SCHEMA>;
type ProfileElement = z.input<typeof ProfileModule.SCHEMA>;

export interface ChunithmBestOptions {
    /**
     * Theme id without the variant suffix, for example `jp-verse-landscape`.
     */
    name: string;
    displayName: string;
    borderColor: string;
    achievements: SpriteDirs<ChunithmAchievementKey>;
    /**
     * File name overrides, for versions that never got artwork for a rank.
     */
    achievementFiles?: Partial<Record<ChunithmAchievementKey, string>>;
    ratingNumberMap?: SpriteDirs<ChunithmRatingNumberMapKey>;
}

interface GridPlacement {
    x: number;
    y: number;
    horizontalSize: number;
    verticalSize: number;
    region: "new" | "old";
}

function scoreGrid(ctx: ThemeContext, options: ChunithmBestOptions, placement: GridPlacement): ScoreGridElement {
    return {
        type: "score-grid",
        x: placement.x,
        y: placement.y,
        horizontalSize: placement.horizontalSize,
        verticalSize: placement.verticalSize,
        region: placement.region,
        index: 0,
        scoreBubble: {
            width: 290,
            height: 155,
            margin: 10,
            gap: 20,
            color: chunithmDifficultyColors,
        },
        sprites: {
            achievement: chunithmAchievements(ctx, options.achievements, options.achievementFiles),
            milestone: chunithmMilestones(ctx),
        },
    };
}

function profile(ctx: ThemeContext, options: ChunithmBestOptions, placement: { x: number; y: number; height: number }): ProfileElement {
    return {
        type: "profile",
        x: placement.x,
        y: placement.y,
        height: placement.height,
        sprites: {
            ratingNumberMap: chunithmRatingNumberMap(ctx, options.ratingNumberMap),
            profile: chunithmProfile(ctx),
        },
    };
}

const footerContent = "Generated by saltbot | chunithm.cab/discord | chunithm.cab/invite";
const hitokotoLines = ["hitokoto/general.json", "hitokoto/support/chunithm.json"];

/**
 * Wide layout showing the new and old score boards side by side.
 */
export function chunithmBestNew(ctx: ThemeContext, options: ChunithmBestOptions, images: ImageOptions[]): ChunithmBestTheme {
    const borderColor = options.borderColor;
    return {
        displayName: options.displayName,
        name: `${options.name}-new`,
        width: 2920,
        height: 1340,
        elements: [
            ...images.map((img) => image(ctx, img)),
            scoreGrid(ctx, options, { x: 70, y: 400, horizontalSize: 4, verticalSize: 5, region: "new" }),
            scoreGrid(ctx, options, { x: 1330, y: 225, horizontalSize: 5, verticalSize: 6, region: "old" }),
            profile(ctx, options, { x: 100, y: 100, height: 320 }),
            text({ size: 32, x: 2840, y: 1307, borderColor, align: "right", content: footerContent }),
            text({ size: 24, x: 910, y: 278, borderColor, align: "left", content: "NEW\nOLD\nNAIVE 30/50" }),
            text({
                size: 24,
                x: 1070,
                y: 278,
                borderColor,
                align: "left",
                content: "average: {newScoreRatingAvg}\naverage: {oldScoreRatingAvg}\naverage: {naiveBest30}/{naiveBest50}",
            }),
            hitokoto(ctx, {
                size: 24,
                x: 80,
                y: 1303,
                borderColor,
                align: "left",
                width: 1000,
                linebreak: true,
                probability: 0.1,
                customLines: hitokotoLines,
            }),
            text({ size: 32, x: 2880, y: 72, borderColor, align: "right", content: "{dateTime}" }),
        ],
    };
}

/**
 * Taller layout with a narrow recent board beside the best board.
 */
export function chunithmBestRecents(ctx: ThemeContext, options: ChunithmBestOptions, images: ImageOptions[]): ChunithmBestTheme {
    const borderColor = options.borderColor;
    return {
        displayName: options.displayName,
        name: `${options.name}-recents`,
        width: 2320,
        height: 1440,
        elements: [
            ...images.map((img) => image(ctx, img)),
            scoreGrid(ctx, options, { x: 70, y: 500, horizontalSize: 2, verticalSize: 5, region: "new" }),
            scoreGrid(ctx, options, { x: 730, y: 325, horizontalSize: 5, verticalSize: 6, region: "old" }),
            profile(ctx, options, { x: 50, y: 50, height: 300 }),
            text({ size: 32, x: 2240, y: 1407, borderColor, align: "right", content: footerContent }),
            text({ size: 24, x: 80, y: 405, borderColor, align: "left", content: "RECENT\nBEST\nNAIVE 50" }),
            text({ size: 11, x: 147, y: 438, borderColor, align: "left", content: "NAIVE 30" }),
            text({
                size: 24,
                x: 210,
                y: 405,
                borderColor,
                align: "left",
                content: "scores average: {newScoreRatingAvg}\nscores average: {oldScoreRatingAvg}\nscores average: {naiveBest50}",
            }),
            hitokoto(ctx, {
                size: 24,
                x: 80,
                y: 1403,
                borderColor,
                align: "left",
                width: 1000,
                linebreak: true,
                probability: 0.1,
                customLines: hitokotoLines,
            }),
            text({ size: 32, x: 2280, y: 72, borderColor, align: "right", content: "{dateTime}" }),
        ],
    };
}
