import type { ChartPainter } from "@chunithm/painter/chart";
import type { ChartGridModule } from "@chunithm/painter/modules/chartGrid";
import type { DetailInfoModule } from "@chunithm/painter/modules/detailInfo";
import type { ProfileModule } from "@chunithm/painter/modules/profile";
import {
    type ChunithmAchievementKey,
    chunithmAchievements,
    chunithmMilestones,
    chunithmProfile,
    chunithmRatingNumberMap,
} from "@theme-tools/chunithm/sprites";
import { hitokoto, type ImageOptions, image, text } from "@theme-tools/common/elements";
import { chunithmDifficultyColors } from "@theme-tools/common/palette";
import type { ThemeContext } from "@theme-tools/lib/context";
import type { SpriteDirs } from "@theme-tools/lib/sprites";
import type { z } from "zod/v4";

export type ChunithmChartTheme = z.input<typeof ChartPainter.THEME>;
type ChartGridElement = z.input<typeof ChartGridModule.SCHEMA>;
type DetailInfoElement = z.input<typeof DetailInfoModule.SCHEMA>;
type ProfileElement = z.input<typeof ProfileModule.SCHEMA>;

const chartVersionless = "themes/chunithm/chart/versionless";

/**
 * Minor versions that have their own logo. CHUNITHM ships the same artwork in every region, so a
 * single table covers all of them.
 */
const versions = [100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 200, 205, 210, 215, 220, 225, 230, 240, 245, 250];

function versionSprites(ctx: ThemeContext): ChartGridElement["sprites"]["versions"] {
    return Object.fromEntries(versions.map((v) => [`${v}`, ctx.ref(`${chartVersionless}/logo/jpn/${v}.webp`)]));
}

export interface ChunithmChartOptions {
    name: string;
    displayName: string;
    borderColor: string;
    cardColor: string;
    achievements: SpriteDirs<ChunithmAchievementKey>;
}

function chartGrid(ctx: ThemeContext, options: ChunithmChartOptions): ChartGridElement {
    return {
        type: "chart-grid",
        x: 100,
        y: 262,
        width: 1645,
        height: 1045,
        margin: 70,
        gap: 40,
        bubble: { margin: 20, color: chunithmDifficultyColors },
        color: { card: options.cardColor },
        sprites: {
            achievement: chunithmAchievements(ctx, options.achievements),
            milestone: chunithmMilestones(ctx),
            versions: versionSprites(ctx),
        },
    };
}

function detailInfo(options: ChunithmChartOptions): DetailInfoElement {
    return { type: "detail-info", x: 1845, y: 562, width: 615, height: 745, margin: 40, color: { card: options.cardColor } };
}

function profile(ctx: ThemeContext): ProfileElement {
    return {
        type: "profile",
        x: 150,
        y: 10,
        height: 293,
        sprites: { ratingNumberMap: chunithmRatingNumberMap(ctx), profile: chunithmProfile(ctx) },
    };
}

export function chunithmChart(ctx: ThemeContext, options: ChunithmChartOptions, images: ImageOptions[]): ChunithmChartTheme {
    const borderColor = options.borderColor;
    return {
        displayName: options.displayName,
        name: options.name,
        width: 2560,
        height: 1440,
        elements: [
            ...images.map((img) => image(ctx, img)),
            chartGrid(ctx, options),
            detailInfo(options),
            profile(ctx),
            text({
                size: 32,
                x: 2480,
                y: 1407,
                borderColor,
                align: "right",
                content: "Generated by saltbot | chunithm.cab/discord | chunithm.cab/invite",
            }),
            hitokoto(ctx, {
                size: 24,
                x: 80,
                y: 1403,
                borderColor,
                align: "left",
                width: 1200,
                linebreak: true,
                probability: 0.1,
                customLines: ["hitokoto/general.json", "hitokoto/support/chunithm.json"],
            }),
            text({ size: 32, x: 2520, y: 72, borderColor, align: "right", content: "{dateTime}" }),
        ],
    };
}
