const sharp = require("sharp");
const upath = require("upath");

(async () => {
    const { MaiDraw } = require("../../../../dist");
    const kamai = new MaiDraw.Maimai.Adapters.KamaiTachi();
    MaiDraw.Maimai.Database.setLocalDatabasePath("../maimai-songs-database");
    const painter = new MaiDraw.Maimai.Painters.Best50();

    const fs = require("fs");

    const themes = [
        "cn-2025-landscape",
        "cn-2025-portrait",
        "salt-2026-landscape",
        "jp-finale-landscape",
        "jp-finale-portrait",
        "jp-prismplus-landscape",
        "jp-prismplus-portrait",
        "jp-prism-landscape",
        "jp-prism-portrait",
        "jp-buddiesplus-landscape",
        "jp-buddiesplus-portrait",
        "cn-2024-landscape",
        "cn-2024-portrait",
        "jp-buddies-landscape",
        "jp-buddies-portrait",
    ];
    const type = "full";
    for (let theme of themes) {
        let result = null;
        if (type === "full") {
            result = await painter.drawWithScoreSource(
                kamai,
                { username: "salt" },
                {
                    scale: 1,
                    theme,
                }
            );
        } else {
            result = await MaiDraw.Maimai.Best50.draw(
                "SALT♪☆＊♀∀＃＆＠",
                16384,
                [
                    {
                        chart: {
                            id: 11375,
                            name: "ミルキースター・シューティングスター",
                            difficulty: 0,
                            level: 3,
                            maxDxScore: 123,
                        },
                        combo: 0,
                        sync: 0,
                        achievement: 51.2345,
                        dxScore: 12,
                        dxRating: 8,
                    },
                    {
                        chart: {
                            id: 647,
                            name: "エイリアンエイリアン",
                            difficulty: 1,
                            level: 8,
                            maxDxScore: 234,
                        },
                        combo: 1,
                        sync: 1,
                        achievement: 62.3456,
                        dxScore: 123,
                        dxRating: 18,
                    },
                    {
                        chart: {
                            id: 10690,
                            name: "ダンスロボットダンス",
                            difficulty: 2,
                            level: 11.6,
                            maxDxScore: 345,
                        },
                        combo: 2,
                        sync: 2,
                        achievement: 83.4567,
                        dxScore: 234,
                        dxRating: 128,
                    },
                    {
                        chart: {
                            id: 11600,
                            name: "感情ディシーブ",
                            difficulty: 3,
                            level: 13.0,
                            maxDxScore: 456,
                        },
                        combo: 3,
                        sync: 3,
                        achievement: 97.8901,
                        dxScore: 345,
                        dxRating: 238,
                    },
                    {
                        chart: {
                            id: 11637,
                            name: "バグ",
                            difficulty: 4,
                            level: 13.9,
                            maxDxScore: 567,
                        },
                        combo: 4,
                        sync: 4,
                        achievement: 98.1234,
                        dxScore: 456,
                        dxRating: 348,
                    },
                    {
                        chart: {
                            id: 834,
                            name: "PANDORA PARADOXXX",
                            difficulty: 5,
                            level: 15.9,
                            maxDxScore: 678,
                        },
                        combo: 4,
                        sync: 5,
                        achievement: 99.1234,
                        dxScore: 567,
                        dxRating: 458,
                    },
                    {
                        chart: {
                            id: 11555,
                            name: "ヒバリ",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 0,
                        sync: 0,
                        achievement: 100.1019,
                        dxScore: 1700,
                        dxRating: 289.73493936,
                    },
                    {
                        chart: {
                            id: 11563,
                            name: "キャットラビング",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 0,
                        sync: 0,
                        achievement: 100.6423,
                        dxScore: 1687,
                        dxRating: 288.1536,
                    },
                    {
                        chart: {
                            id: 11650,
                            name: "ずんだもんの朝食　〜目覚ましずんラップ〜",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 2,
                        achievement: 100.3416,
                        dxScore: 2008,
                        dxRating: 286.09396992,
                    },
                    {
                        chart: {
                            id: 11596,
                            name: "Vallista",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.5175,
                        dxScore: 1395,
                        dxRating: 281.4,
                    },
                    {
                        chart: {
                            id: 10315,
                            name: "深海少女",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 0,
                        sync: 0,
                        achievement: 100.0051,
                        dxScore: 0,
                        dxRating: 280.8143208,
                    },
                    {
                        chart: {
                            id: 11560,
                            name: "阿修羅ちゃん",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 0,
                        sync: 1,
                        achievement: 99.8646,
                        dxScore: 1880,
                        dxRating: 278.14288392,
                    },
                    {
                        chart: {
                            id: 11589,
                            name: "DROPS feat. Such",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 99.8213,
                        dxScore: 1694,
                        dxRating: 278.02228476,
                    },
                    {
                        chart: {
                            id: 11526,
                            name: "トノサマビーム",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.1681,
                        dxScore: 2323,
                        dxRating: 276.94476288,
                    },
                    {
                        chart: {
                            id: 11592,
                            name: "花となれ",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.7423,
                        dxScore: 883,
                        dxRating: 274.6464,
                    },
                ],
                [
                    {
                        chart: {
                            id: 11451,
                            name: "Transcend Lights",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.7521,
                        dxScore: 1657,
                        dxRating: 303.912,
                    },
                    {
                        chart: {
                            id: 11568,
                            name: "INTERNET OVERDOSE",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 0,
                        sync: 1,
                        achievement: 100.6577,
                        dxScore: 2220,
                        dxRating: 303.912,
                    },
                    {
                        chart: {
                            id: 11488,
                            name: "スカーレット警察のゲットーパトロール24時",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.5492,
                        dxScore: 1939,
                        dxRating: 303.912,
                    },
                    {
                        chart: {
                            id: 835,
                            name: "Believe the Rainbow",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.9224,
                        dxScore: 1245,
                        dxRating: 301.6608,
                    },
                    {
                        chart: {
                            id: 417,
                            name: "ウミユリ海底譚",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.8178,
                        dxScore: 1976,
                        dxRating: 301.6608,
                    },
                    {
                        chart: {
                            id: 11433,
                            name: "ヒトガタ",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 1,
                        achievement: 100.6644,
                        dxScore: 2082,
                        dxRating: 301.6608,
                    },
                    {
                        chart: {
                            id: 764,
                            name: "フィクサ ー",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 1,
                        achievement: 100.6095,
                        dxScore: 2066,
                        dxRating: 301.6608,
                    },
                    {
                        chart: {
                            id: 11504,
                            name: "ばかみたい【Taxi Driver Edition】",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.5023,
                        dxScore: 729,
                        dxRating: 301.6608,
                    },
                    {
                        chart: {
                            id: 566,
                            name: "天火明命",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.0184,
                        dxScore: 1888,
                        dxRating: 300.29524416,
                    },
                    {
                        chart: {
                            id: 11437,
                            name: "三妖精SAY YA!!!",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 1,
                        achievement: 100.7484,
                        dxScore: 2217,
                        dxRating: 299.4096,
                    },
                    {
                        chart: {
                            id: 674,
                            name: "Magical Flavor",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.5723,
                        dxScore: 1531,
                        dxRating: 299.4096,
                    },
                    {
                        chart: {
                            id: 11355,
                            name: "ラグトレイン",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 3,
                        sync: 0,
                        achievement: 100.9318,
                        dxScore: 2162,
                        dxRating: 297.1584,
                    },
                    {
                        chart: {
                            id: 11523,
                            name: "ViRTUS",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.619,
                        dxScore: 1902,
                        dxRating: 297.1584,
                    },
                    {
                        chart: {
                            id: 734,
                            name: "ENERGY SYNERGY MATRIX",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.7419,
                        dxScore: 0,
                        dxRating: 292.656,
                    },
                    {
                        chart: {
                            id: 11429,
                            name: "Love's Theme of BADASS ～バッド・アス 愛のテーマ～",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.6013,
                        dxScore: 2108,
                        dxRating: 292.656,
                    },
                    {
                        chart: {
                            id: 11311,
                            name: "躯樹の墓守",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.553,
                        dxScore: 0,
                        dxRating: 292.656,
                    },
                    {
                        chart: {
                            id: 11401,
                            name: "コスモポップファンクラブ",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.5111,
                        dxScore: 0,
                        dxRating: 292.656,
                    },
                    {
                        chart: {
                            id: 11289,
                            name: "ベースラインやってる？笑",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.4342,
                        dxScore: 1888,
                        dxRating: 290.69674848,
                    },
                    {
                        chart: {
                            id: 836,
                            name: "Good Bye, Mr. Jack",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.6728,
                        dxScore: 0,
                        dxRating: 290.4048,
                    },
                    {
                        chart: {
                            id: 11410,
                            name: "ヴァンパイア",
                            difficulty: 4,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.0379,
                        dxScore: 1974,
                        dxRating: 289.54969776,
                    },
                    {
                        chart: {
                            id: 793,
                            name: "ロキ",
                            difficulty: 4,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 0,
                        sync: 0,
                        achievement: 100.4615,
                        dxScore: 2216,
                        dxRating: 288.6057972,
                    },
                    {
                        chart: {
                            id: 11485,
                            name: "フォニイ",
                            difficulty: 4,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 0,
                        sync: 0,
                        achievement: 100.4614,
                        dxScore: 1995,
                        dxRating: 288.60550992,
                    },
                    {
                        chart: {
                            id: 308,
                            name: "Back 2 Back",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 99.8058,
                        dxScore: 1027,
                        dxRating: 288.50862606,
                    },
                    {
                        chart: {
                            id: 11422,
                            name: "　",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.7672,
                        dxScore: 1666,
                        dxRating: 288.1536,
                    },
                    {
                        chart: {
                            id: 11184,
                            name: "Virtual to LIVE",
                            difficulty: 4,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.7657,
                        dxScore: 1862,
                        dxRating: 288.1536,
                    },
                    {
                        chart: {
                            id: 11517,
                            name: "最強STRONGER",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.7021,
                        dxScore: 0,
                        dxRating: 288.1536,
                    },
                    {
                        chart: {
                            id: 11572,
                            name: "tape/stop/night",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.686,
                        dxScore: 1526,
                        dxRating: 288.1536,
                    },
                    {
                        chart: {
                            id: 772,
                            name: "FREEDOM DiVE (tpz Overcute Remix)",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 3,
                        achievement: 100.5016,
                        dxScore: 1803,
                        dxRating: 288.1536,
                    },
                    {
                        chart: {
                            id: 690,
                            name: "ダンスロボットダンス",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.2329,
                        dxScore: 2201,
                        dxRating: 287.94907512,
                    },
                    {
                        chart: {
                            id: 621,
                            name: "ARROW",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.1502,
                        dxScore: 0,
                        dxRating: 287.71149456,
                    },
                    {
                        chart: {
                            id: 689,
                            name: "Credits",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 1,
                        sync: 0,
                        achievement: 100.1448,
                        dxScore: 861,
                        dxRating: 287.69598144,
                    },
                    {
                        chart: {
                            id: 189,
                            name: "弱虫モンブラン",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 4,
                        sync: 0,
                        achievement: 101,
                        dxScore: 1312,
                        dxRating: 285.9024,
                    },
                    {
                        chart: {
                            id: 11520,
                            name: "独りんぼ エンヴィー",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.822,
                        dxScore: 1642,
                        dxRating: 285.9024,
                    },
                    {
                        chart: {
                            id: 432,
                            name: "幸せになれる隠しコマンドがあるらしい",
                            difficulty: 2,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.719,
                        dxScore: 1462,
                        dxRating: 285.9024,
                    },
                    {
                        chart: {
                            id: 603,
                            name: "その群青が愛しかったようだった",
                            difficulty: 3,
                            level: 13.7,
                            maxDxScore: 6666,
                        },
                        combo: 2,
                        sync: 0,
                        achievement: 100.702,
                        dxScore: 0,
                        dxRating: 285.9024,
                    },
                ],
                {
                    scale: 2,
                    theme,
                }
            );
        }
        if (result) {
            fs.writeFileSync(
                upath.join(__dirname, `${theme}.webp`),
                await sharp(result)
                    .webp({
                        quality: 100,
                    })
                    .toBuffer()
            );
            console.log(`${theme} passed.`);
        } else {
            console.log(`${theme} failed!`);
        }
    }
    process.exit(0);
})();
