import type { Best50Painter } from "@ongeki/painter/best";
import type { ProfileModule } from "@ongeki/painter/modules/profile";
import type { ScoreGridModule } from "@ongeki/painter/modules/scoreGrid";
import { hitokoto, type ImageOptions, image, text } from "@theme-tools/common/elements";
import { ongekiDifficultyColors } from "@theme-tools/common/palette";
import type { ThemeContext } from "@theme-tools/lib/context";
import { ongekiAchievements, ongekiMilestones, ongekiProfileSprites, ongekiVersionless } from "@theme-tools/ongeki/sprites";
import type { z } from "zod/v4";

export type OngekiBestTheme = z.input<typeof Best50Painter.THEME>;
type ScoreGridElement = z.input<typeof ScoreGridModule.SCHEMA>;
type ProfileElement = z.input<typeof ProfileModule.SCHEMA>;

export interface OngekiBestOptions {
    /**
     * Theme id without the variant suffix, for example `jp-refresh-landscape`.
     */
    name: string;
    displayName: string;
    borderColor: string;
    /**
     * Artwork directory of this version, relative to `assets/`.
     */
    art: string;
}

interface GridPlacement {
    x: number;
    y: number;
    horizontalSize: number;
    verticalSize: number;
    region: "recent" | "new" | "old";
    index?: number;
    width?: number;
    gap?: number | { x: number; y: number };
    strictScoreCount?: number;
}

function scoreGrid(ctx: ThemeContext, placement: GridPlacement): ScoreGridElement {
    return {
        type: "score-grid",
        x: placement.x,
        y: placement.y,
        horizontalSize: placement.horizontalSize,
        verticalSize: placement.verticalSize,
        region: placement.region,
        index: placement.index ?? 0,
        scoreBubble: {
            width: placement.width ?? 290,
            height: 155,
            margin: 10,
            gap: placement.gap ?? 20,
            color: ongekiDifficultyColors,
            strictScoreCount: placement.strictScoreCount,
        },
        sprites: {
            achievement: ongekiAchievements(ctx),
            milestone: ongekiMilestones(ctx),
        },
    };
}

function profile(ctx: ThemeContext): ProfileElement {
    return { type: "profile", x: 0, y: 0, sprites: ongekiProfileSprites(ctx) };
}

/**
 * The naive rating sits on top of the profile plate artwork, so it is drawn in black with a fully
 * transparent border rather than the theme's accent colour.
 */
function naiveRating(x: number, y: number) {
    return text({ size: 24, x, y, color: "black", borderColor: "rgba(255, 255, 255, 0)", align: "left", content: "{naiveRatingAverage}" });
}

const footerContent = "Generated by saltbot | ongeki.cab/discord | ongeki.cab/invite";
const hitokotoLines = ["hitokoto/general.json", "hitokoto/support/ongeki.json"];

/**
 * Pre Re:Fresh layout: recent and old boards on top, the new board underneath.
 */
export function ongekiBestClassic(ctx: ThemeContext, options: OngekiBestOptions, logo: ImageOptions): OngekiBestTheme {
    const borderColor = options.borderColor;
    return {
        displayName: options.displayName,
        name: `${options.name}-classic`,
        width: 2320,
        height: 2215,
        elements: [
            image(ctx, { x: 0, y: -1130, width: 2320, height: 4124, path: `${options.art}/background.webp` }),
            scoreGrid(ctx, { x: 70, y: 425, horizontalSize: 2, verticalSize: 5, region: "recent" }),
            scoreGrid(ctx, { x: 720, y: 425, horizontalSize: 5, verticalSize: 6, region: "old" }),
            scoreGrid(ctx, { x: 70, y: 1360, horizontalSize: 1, verticalSize: 1, region: "new" }),
            scoreGrid(ctx, { x: 70, y: 1535, horizontalSize: 7, verticalSize: 2, region: "new", index: 1, gap: { x: 25, y: 20 } }),
            image(ctx, logo),
            image(ctx, { x: 460, y: 1330, width: 161, height: 180, path: `${ongekiVersionless}/emote.webp` }),
            text({ size: 32, x: 2240, y: 1932, borderColor, align: "right", content: footerContent }),
            text({ size: 24, x: 80, y: 405, borderColor, align: "left", content: "RECENT scores average: {recentOrPlatinumScoreAvg}" }),
            text({ size: 24, x: 730, y: 405, borderColor, align: "left", content: "OLD scores average: {oldScoreRatingAvg}" }),
            text({ size: 24, x: 80, y: 1340, borderColor, align: "left", content: "NEW average: {newScoreRatingAvg}" }),
            naiveRating(250, 330),
            hitokoto(ctx, {
                size: 24,
                x: 80,
                y: 1928,
                borderColor,
                align: "left",
                width: 1000,
                linebreak: true,
                probability: 0.1,
                customLines: hitokotoLines,
            }),
            profile(ctx),
            text({ size: 32, x: 2300, y: 397, borderColor, align: "right", content: "{dateTime}" }),
        ],
    };
}

/**
 * Re:Fresh layout: tall new and old boards, with the 50 platinum scores in a wide strip below.
 */
export function ongekiBestRefresh(ctx: ThemeContext, options: OngekiBestOptions, logo: ImageOptions): OngekiBestTheme {
    const borderColor = options.borderColor;
    return {
        displayName: options.displayName,
        name: `${options.name}-refresh`,
        width: 2000,
        height: 3208,
        elements: [
            image(ctx, { x: 1000, y: 1604, align: "cc", width: 2000, path: `${options.art}/background.webp` }),
            scoreGrid(ctx, { x: 70, y: 377, horizontalSize: 1, verticalSize: 10, region: "new" }),
            scoreGrid(ctx, { x: 400, y: 377, horizontalSize: 5, verticalSize: 10, region: "old" }),
            scoreGrid(ctx, {
                x: 70,
                y: 2177,
                horizontalSize: 13,
                verticalSize: 4,
                region: "recent",
                width: 115,
                gap: 30.41666666666666,
                strictScoreCount: 50,
            }),
            image(ctx, { x: 1800, y: 2811, align: "cc", width: 260, path: `${ongekiVersionless}/emote2.webp` }),
            text({ size: 32, x: 1920, y: 2959, borderColor, align: "right", content: footerContent }),
            text({ size: 24, x: 80, y: 357, borderColor, align: "left", content: "NEW average: {newScoreRatingAvg}" }),
            text({ size: 24, x: 410, y: 357, borderColor, align: "left", content: "OLD average: {oldScoreRatingAvg}" }),
            text({ size: 24, x: 80, y: 2157, borderColor, align: "left", content: "PLATINUM bonus: +{recentOrPlatinumScoreAvg}" }),
            hitokoto(ctx, {
                size: 24,
                x: 80,
                y: 2955,
                borderColor,
                align: "left",
                width: 800,
                linebreak: true,
                probability: 0.1,
                customLines: hitokotoLines,
            }),
            image(ctx, logo),
            naiveRating(210, 282),
            profile(ctx),
            text({ size: 32, x: 1980, y: 347, borderColor, align: "right", content: "{dateTime}" }),
        ],
    };
}
