import type { ChartPainter } from "@ongeki/painter/chart";
import type { CharacterInfoModule } from "@ongeki/painter/modules/characterInfo";
import type { ChartGridModule } from "@ongeki/painter/modules/chartGrid";
import type { DetailInfoModule } from "@ongeki/painter/modules/detailInfo";
import type { ProfileModule } from "@ongeki/painter/modules/profile";
import { hitokoto, type ImageOptions, image, text } from "@theme-tools/common/elements";
import { ongekiDifficultyColors } from "@theme-tools/common/palette";
import type { ThemeContext } from "@theme-tools/lib/context";
import { ongekiAchievements, ongekiMilestones, ongekiProfileSprites } from "@theme-tools/ongeki/sprites";
import type { z } from "zod/v4";

export type OngekiChartTheme = z.input<typeof ChartPainter.THEME>;
type ChartGridElement = z.input<typeof ChartGridModule.SCHEMA>;
type DetailInfoElement = z.input<typeof DetailInfoModule.SCHEMA>;
type CharacterInfoElement = z.input<typeof CharacterInfoModule.SCHEMA>;
type ProfileElement = z.input<typeof ProfileModule.SCHEMA>;

const chartVersionless = "themes/ongeki/chart/versionless";

/**
 * Minor versions that have their own logo. ONGEKI only ever released in Japan, so there is one region.
 */
const jpnVersions = [100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150];

export interface OngekiChartOptions {
    name: string;
    displayName: string;
    borderColor: string;
    cardColor: string;
    art: string;
}

function chartGrid(ctx: ThemeContext, options: OngekiChartOptions): ChartGridElement {
    return {
        type: "chart-grid",
        x: 100,
        y: 1157,
        width: 1395,
        height: 1045,
        margin: 70,
        gap: 40,
        bubble: { margin: 20, color: ongekiDifficultyColors },
        color: { card: options.cardColor },
        sprites: {
            achievement: ongekiAchievements(ctx),
            milestone: ongekiMilestones(ctx),
            // biome-ignore lint/style/useNamingConvention: region key is fixed by the module schema
            versions: { JPN: Object.fromEntries(jpnVersions.map((v) => [`${v}`, ctx.ref(`${chartVersionless}/logo/jpn/${v}.webp`)])) },
        },
    };
}

function detailInfo(options: OngekiChartOptions): DetailInfoElement {
    return { type: "detail-info", x: 100, y: 312, width: 615, height: 745, margin: 40, color: { card: options.cardColor } };
}

function characterInfo(options: OngekiChartOptions): CharacterInfoElement {
    return { type: "character-info", x: 815, y: 312, width: 685, height: 745, margin: 40, color: { card: options.cardColor } };
}

function profile(ctx: ThemeContext): ProfileElement {
    return { type: "profile", x: 0, y: 0, sprites: ongekiProfileSprites(ctx) };
}

export function ongekiChart(ctx: ThemeContext, options: OngekiChartOptions, background: ImageOptions): OngekiChartTheme {
    const borderColor = options.borderColor;
    return {
        displayName: options.displayName,
        name: options.name,
        width: 1595,
        height: 2502,
        elements: [
            image(ctx, background),
            chartGrid(ctx, options),
            detailInfo(options),
            characterInfo(options),
            image(ctx, { x: 1180, y: 820, width: 310, height: 251, path: `${options.art}/logo.webp` }),
            text({ size: 32, x: 80, y: 2272, borderColor, align: "left", content: "Generated by saltbot |" }),
            text({ size: 28, x: 465, y: 2252, borderColor, align: "left", content: "ongeki.cab/invite\nongeki.cab/discord" }),
            hitokoto(ctx, {
                size: 24,
                x: 1515,
                y: 2252,
                borderColor,
                align: "right",
                width: 580,
                linebreak: true,
                probability: 0.1,
                customLines: ["hitokoto/general.json", "hitokoto/support/ongeki.json"],
            }),
            profile(ctx),
            text({ size: 32, x: 407, y: 287, borderColor, align: "center", content: "{dateTime}" }),
        ],
    };
}
